const SALON = {
  name: 'Trial Salon Demo', location: 'Kololo, Kampala, Uganda', address: 'An imagined salon in the heart of Kololo.', hours: 'Monday–Saturday · 9am–7pm', sunday: 'Sunday · 10am–4pm', email: 'hello@trialsalon.example', whatsapp: null,
  images: { hero: 'finished-hairstyle-compressed.jpg', interior: 'salon-interior-compressed.jpg', styling: 'women-hair-styling-compressed.jpg', braiding: 'braiding-service-compressed.jpg', barber: 'barber-service-compressed.jpg', treatment: 'hair-treatment-compressed.jpg', nails: 'manicure-services-compressed.jpg', haircut: 'finished-mens-haircut-compressed.jpg', atmosphere: 'salon-atmosphere-compressed.jpg', details: 'salon-details-compressed.jpg' },
  categories: [
    {id:'hair',name:'Hair styling',image:'styling',intro:'Good hair. Your way.',description:'From a fresh shape to a beautifully finished blowout. Considered styling that feels like you.',services:[{id:'blowout',name:'Signature wash & blowout',price:45000,duration:'60 min',description:'A cleansing wash, nourishing condition and a polished finish.'},{id:'cut',name:'Cut & finish',price:60000,duration:'75 min',description:'A personal consultation, precision shape and finished style.'},{id:'occasion',name:'Occasion styling',price:90000,duration:'90 min',description:'An elegant updo or sculpted waves for your special plans.'}]},
    {id:'braids',name:'Braiding',image:'braiding',intro:'Every braid, considered.',description:'Beautiful protective styles, made with patience, care and an eye for detail.',services:[{id:'cornrows',name:'Classic cornrows',price:50000,duration:'90 min',description:'Clean, carefully sectioned cornrows. Natural hair styles.'},{id:'knotless',name:'Knotless braids',price:150000,duration:'4–6 hours',description:'Medium, shoulder-length braids. Extensions priced separately.'},{id:'twists',name:'Two-strand twists',price:80000,duration:'2 hours',description:'Soft, defined twists for natural hair.'}]},
    {id:'barber',name:'Barbering',image:'barber',intro:'Sharp lines. Easy confidence.',description:'Modern cuts and precise grooming, with time taken over the little things.',services:[{id:'mens-cut',name:'Signature haircut',price:30000,duration:'45 min',description:'Consultation, tailored cut and styling.'},{id:'beard',name:'Beard shape & finish',price:20000,duration:'30 min',description:'Precise shaping and a conditioning finish.'},{id:'cut-beard',name:'Cut & beard ritual',price:45000,duration:'60 min',description:'Our signature cut with a complete beard tidy.'}]},
    {id:'treatments',name:'Hair treatments',image:'treatment',intro:'A little time to restore.',description:'Thoughtful care for your hair and scalp. Leave feeling lighter, softer, renewed.',services:[{id:'deep-condition',name:'Deep conditioning ritual',price:50000,duration:'60 min',description:'A moisture-rich treatment with gentle steam.'},{id:'scalp',name:'Scalp care & massage',price:40000,duration:'45 min',description:'A cleansing scalp ritual and relaxing massage.'}]},
    {id:'nails',name:'Nails',image:'nails',intro:'Beauty in the details.',description:'Neatly shaped, beautifully finished. A small ritual that makes all the difference.',services:[{id:'manicure',name:'Classic manicure',price:30000,duration:'45 min',description:'Nail shaping, cuticle care and regular polish.'},{id:'gel',name:'Gel manicure',price:50000,duration:'60 min',description:'A full manicure with a lasting gel finish.'},{id:'pedicure',name:'Signature pedicure',price:45000,duration:'60 min',description:'A soothing soak, foot care and polish.'}]},
    {id:'beauty',name:'Beauty services',image:'details',intro:'The finishing touch.',description:'Subtle definition or a little occasion glamour. Always unmistakably you.',services:[{id:'brows',name:'Brow shaping',price:15000,duration:'20 min',description:'Careful shaping to complement your natural features.'},{id:'makeup',name:'Soft-glam makeup',price:100000,duration:'75 min',description:'Fresh, softly defined makeup for your next occasion.'}]}
  ],
  gallery: [{image:'hero',title:'Softness, with a statement',category:'Hair styling'},{image:'haircut',title:'A fresh perspective',category:'Barbering'},{image:'braiding',title:'The art of the braid',category:'Braiding'},{image:'nails',title:'Perfectly polished',category:'Nails'},{image:'atmosphere',title:'Settle into your moment',category:'Our space'},{image:'treatment',title:'Care from the roots',category:'Hair treatments'}],
  testimonials: [{quote:'They took the time to understand what I wanted. I left feeling like myself, just a little more confident.',name:'Nadia K.',service:'Cut & finish'},{quote:'A beautiful space, a warm welcome, and braids that felt as good as they looked.',name:'Patricia A.',service:'Knotless braids'},{quote:'The little details make the difference. This is exactly how a moment of self-care should feel.',name:'Daniel M.',service:'Cut & beard ritual'}]
};
const money = value => 'UGX ' + value.toLocaleString('en-UG');
const findService = id => SALON.categories.flatMap(c => c.services.map(s => ({...s,category:c.name,categoryId:c.id}))).find(s => s.id === id);
