const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const main=$('main');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=(key,alt,cls='',eager=false)=>`<img src="${SALON.images[key]}" alt="${alt}" class="${cls}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const cta=(text='Book appointment',id='',cls='btn')=>`<a class="${cls}" href="#book${id?'?service='+id:''}">${text}<span aria-hidden="true">↗</span></a>`;
let category='hair',page='',quote=0,photoIndex=0,origin;
function home(){main.innerHTML=`<section class="hero" id="home"><div class="hero-top"><span><b class="dot"></b> GOOD LOOKS. GREAT ENERGY.</span><span>KOLOLO, KAMPALA ↗</span></div><div class="hero-grid"><div class="hero-copy"><h1>YOUR LOOK.<br>YOUR <span>ENERGY.</span></h1><p>Fresh hair. Sharp cuts. A whole new mood.<br>Your next favourite look starts right here.</p>${cta('Let’s book your look')}<a class="hero-explore" href="#services">Find your service ↓</a><div class="hero-foot"><span class="asterisk">✳</span><p>ALL STYLES. ALL PERSONALITIES.<br>ONE VERY GOOD SALON.</p></div></div><div class="hero-visual">${img('hero','Finished curls and a confident fresh hairstyle','hero-main',true)}<div class="photo-sticker">FRESH LOOK.<br><strong>SAME YOU.</strong><span>↗</span></div><figure class="hero-inset">${img('haircut','A sharply finished men’s haircut','',true)}<figcaption>THE FRESH-CUT FEELING.</figcaption></figure><span class="hero-vertical">LOOK GOOD. FEEL LIKE YOU.</span></div></div></section><div class="ticker" aria-label="Hair, braids, barber, treatments, nails and beauty"><div aria-hidden="true">${Array(2).fill('HAIR <span>✳</span> BRAIDS <span>✳</span> BARBER <span>✳</span> NAILS <span>✳</span> BEAUTY <span>✳</span> ').join('')}</div></div>
<section class="section explorer" id="services"><div class="section-head reveal"><div><p class="eyebrow">01 / FIND YOUR NEXT LOOK</p><h2>PICK YOUR<br><span>GOOD-HAIR DAY.</span></h2></div><p>Choose your thing. Check the price.<br>Book it in a few easy steps.</p></div><div class="tabs" role="tablist" aria-label="Service categories">${SALON.categories.map(c=>`<button id="tab-${c.id}" role="tab" aria-controls="service-panel" aria-selected="${c.id===category}" tabindex="${c.id===category?0:-1}" data-cat="${c.id}">${c.name}<span>↗</span></button>`).join('')}</div><div id="service-panel" role="tabpanel"></div><p class="fine">Demo prices in UGX. Final quote depends on hair length and style. Extensions are extra where stated.</p></section>
<section class="about section" id="about"><div class="about-photo reveal">${img('interior','Warm salon interior and styling stations')}<span class="about-label">YOUR NEW<br>HAPPY PLACE. ☺</span></div><div class="about-copy reveal"><p class="eyebrow">02 / MORE THAN A MIRROR MOMENT</p><h2>COME FOR<br>THE LOOK.<br><span>STAY FOR<br>THE VIBE.</span></h2><p>We’re Trial. An imagined neighbourhood salon in Kololo with a simple idea: great style should feel like you.</p><p>Bring the inspo, the big change, or your usual. We bring thoughtful care, good conversation and attention to every last detail.</p></div></section>
<section class="favourites section"><div class="section-head"><div><p class="eyebrow">THE QUICK PICKS</p><h2>BIG MOOD.<br>SMALL DECISION.</h2></div><p>Three ways to hit refresh.<br>Jump straight into your booking.</p></div><div class="favourite-strip" role="region" aria-label="Quick Picks — swipe to browse three popular services">${['knotless','cut-beard','gel'].map((id,i)=>{const s=findService(id);const c=SALON.categories.find(c=>c.id===s.categoryId);return `<article><a href="#book?service=${id}" class="favourite-image" aria-label="Book ${s.name}">${img(c.image,s.name)}<span>0${i+1} / ${c.name.toUpperCase()}</span><b>↗</b></a><div><h3>${s.name}</h3><span>${money(s.price)}</span></div>${cta('Book this service',id,'link')}</article>`}).join('')}</div></section>
<section class="why section"><p class="eyebrow">THE TRIAL DIFFERENCE</p><h2>GOOD HANDS.<br><span>BETTER ENERGY.</span></h2><div class="why-list"><article><span>01</span><div><h3>Your look, listened to.</h3><p>We start with a conversation, so the finish feels like you.</p></div></article><article><span>02</span><div><h3>Care that goes all in.</h3><p>From a clean section to a sharp line. The details matter.</p></div></article><article><span>03</span><div><h3>Everyone’s kind of space.</h3><p>Warm welcomes. Zero pressure. Room for every style.</p></div></article></div></section>
<section class="work section" id="work"><div class="section-head"><div><p class="eyebrow">03 / THE LOOKBOOK</p><h2>LESS TALK.<br><span>MORE LOOKS.</span></h2></div><div><p>Fresh finishes. Behind-the-chair moments.<br>Swipe, scroll, or take a closer look.</p><div class="slider-buttons"><button id="gallery-back" aria-label="Scroll gallery backwards">←</button><button id="gallery-forward" aria-label="Scroll gallery forwards">→</button></div></div></div><div class="gallery-track" tabindex="0" aria-label="Scrollable salon gallery">${SALON.gallery.map((g,i)=>`<button class="gallery-tile" data-photo="${i}" aria-label="Enlarge ${g.title}">${img(g.image,g.title)}<span><b>${g.title}</b><small>${g.category} ↗</small></span></button>`).join('')}</div><div class="gallery-meter"><span></span></div></section>
<section class="reviews section"><div><p class="eyebrow">GOOD WORDS. GOOD PEOPLE.</p><h2>THE AFTER<br><span>FEELING.</span></h2><p class="fine">Illustrative testimonials for this fictional salon.</p></div><div><div class="review-stars" aria-hidden="true">✳ ✳ ✳ ✳ ✳</div><div id="quote" aria-live="polite"></div><div class="review-controls">${SALON.testimonials.map((_,i)=>`<button data-quote="${i}" aria-label="Show testimonial ${i+1}" aria-pressed="${i===quote}">0${i+1}</button>`).join('')}</div></div></section>
<section class="booking-banner section"><p class="eyebrow">YOUR NEXT ERA IS CALLING.</p><h2>NEW LOOK.<br>LET’S <span>GO. ↗</span></h2><div>${cta('Find my service')}<p>Choose your look. Send a demo request.<br>No payments. No pressure.</p></div></section>
<section class="contact section" id="contact"><div><p class="eyebrow">04 / COME THROUGH</p><h2>FIND US<br>IN <span>KOLOLO.</span></h2><p>${SALON.address}</p><a class="link" href="${SALON.contact.map}" target="_blank" rel="noopener">View the Kololo neighbourhood ↗</a><p class="fine">Neighbourhood map only. This demo has no physical salon premises.</p></div><div class="contact-info"><div><p class="eyebrow">WHEN WE’RE HERE</p><p>${SALON.hours}<br>${SALON.sunday}</p></div><div><p class="eyebrow">GOT A LOOK IN MIND?</p>${cta('Start with a service','','link')}<button class="link" id="share-demo">Share this demo on WhatsApp ↗</button><p class="fine">Choose your own recipient. No real salon number is configured.</p></div></div></section>`;renderServices();renderQuote();wireTabs();wireQuickPicks();$$('[data-photo]').forEach(b=>b.onclick=()=>view(+b.dataset.photo));$$('[data-quote]').forEach(b=>b.onclick=()=>{quote=+b.dataset.quote;renderQuote()});const track=$('.gallery-track');const shift=direction=>shiftGallery(direction);$('#gallery-back').onclick=()=>shift(-1);$('#gallery-forward').onclick=()=>shift(1);track.addEventListener('scroll',()=>updateGallery(),{passive:true});track.onkeydown=e=>{if(e.target===track&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();shift(e.key==='ArrowRight'?1:-1)}};updateGallery();$('#share-demo').onclick=()=>share('Trial Salon Demo — a fictional salon concept in Kololo. Fresh looks. Good energy.');reveal()}
let quickPicksObserver;
function wireQuickPicks(){
 quickPicksObserver?.disconnect();
 const track=$('.favourite-strip'),cards=[...track.querySelectorAll('article')];
 if(!('IntersectionObserver' in window))return;
 const bounds=track.getBoundingClientRect();
 cards.forEach(card=>{const r=card.getBoundingClientRect();card.dataset.preview=String(r.left<bounds.left-1||r.right>bounds.right+1)});
 track.classList.add('with-previews');
 quickPicksObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{
  entry.target.dataset.preview=String(entry.intersectionRatio<.95);
 }),{root:track,threshold:[0,.95,1]});
 cards.forEach(card=>quickPicksObserver.observe(card));
 track.addEventListener('focusin',e=>{
  if(!matchMedia('(max-width:760px)').matches)return;
  const card=e.target.closest('article');if(!card)return;
  track.scrollTo({left:track.scrollLeft+card.getBoundingClientRect().left-track.getBoundingClientRect().left,behavior:motion()});
 });
}
function renderServices(){const c=SALON.categories.find(c=>c.id===category);$$('[data-cat]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.cat===category);b.tabIndex=b.dataset.cat===category?0:-1});const p=$('#service-panel');p.setAttribute('aria-labelledby','tab-'+category);p.innerHTML=`<div class="service-art">${img(c.image,c.name+' service')}<span class="service-art-label">${c.name.toUpperCase()}<b>↗</b></span></div><div class="service-menu"><div class="service-intro"><span class="eyebrow">THE ${c.name.toUpperCase()} LINE-UP</span><h3>${c.intro}</h3><p>${c.description}</p></div>${c.services.map(s=>`<article><div><h4>${s.name}</h4><p>${s.description}</p><small>${s.duration}</small></div><div><strong>${money(s.price)}</strong>${cta('Book this service',s.id,'service-cta')}</div></article>`).join('')}</div>`}
function wireTabs(){$$('[data-cat]').forEach(b=>{b.onclick=()=>{category=b.dataset.cat;renderServices()};b.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const tabs=$$('[data-cat]');const i=tabs.indexOf(b);const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[n].click();tabs[n].focus()}}})}
function shiftGallery(direction){
 const track=$('.gallery-track');if(!track)return;
 if(!matchMedia('(max-width:760px)').matches){track.scrollBy({left:direction*track.clientWidth*.75,behavior:motion()});return}
 const tiles=$$('.gallery-tile',track),left=track.getBoundingClientRect().left;
 let closest=0;
 tiles.forEach((tile,i)=>{if(Math.abs(tile.getBoundingClientRect().left-left)<Math.abs(tiles[closest].getBoundingClientRect().left-left))closest=i});
 const target=tiles[Math.max(0,Math.min(tiles.length-1,closest+direction))];
 track.scrollTo({left:track.scrollLeft+target.getBoundingClientRect().left-left,behavior:motion()});
}
function updateGallery(){
 const t=$('.gallery-track');if(!t)return;
 const max=Math.max(0,t.scrollWidth-t.clientWidth),position=Math.max(0,Math.min(t.scrollLeft,max));
 $('#gallery-back').disabled=position<3;$('#gallery-forward').disabled=position>=max-3;
 $('.gallery-meter span').style.width=`${max?20+80*position/max:100}%`;
 const bounds=t.getBoundingClientRect();
 $$('.gallery-tile',t).forEach(tile=>{const r=tile.getBoundingClientRect();tile.dataset.preview=String(r.left<bounds.left-2||r.right>bounds.right+2)});
}

function renderQuote(){const t=SALON.testimonials[quote];$('#quote').innerHTML=`<blockquote>“${t.quote}”</blockquote><p><strong>${t.name}</strong> / ${t.service}</p>`;$$('[data-quote]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.quote===quote))}
function motion(){return matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}
function reveal(){if(!('IntersectionObserver'in window))return;const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}
const viewer=$('#viewer');function view(i){photoIndex=(i+SALON.gallery.length)%SALON.gallery.length;const g=SALON.gallery[photoIndex];$('img',viewer).src=SALON.images[g.image];$('img',viewer).alt=g.title;$('figcaption',viewer).textContent=`${g.title} · ${photoIndex+1} / ${SALON.gallery.length}`;if(!viewer.open){origin=document.activeElement;viewer.showModal();document.body.classList.add('viewing')}}$('#close-viewer').onclick=()=>viewer.close();$('#prev-photo').onclick=()=>view(photoIndex-1);$('#next-photo').onclick=()=>view(photoIndex+1);viewer.onclose=()=>{document.body.classList.remove('viewing');origin?.focus()};viewer.onclick=e=>{if(e.target===viewer)viewer.close()};viewer.onkeydown=e=>{if(e.key==='ArrowRight')view(photoIndex+1);if(e.key==='ArrowLeft')view(photoIndex-1)};
function share(text){window.open(SALON.contact.whatsappShare+encodeURIComponent(text),'_blank','noopener')}
function closeMenu(){$('header').classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');$('#menu').setAttribute('aria-label','Open navigation')}
$('#menu').onclick=()=>{const open=$('header').classList.toggle('menu-open');$('#menu').setAttribute('aria-expanded',open);$('#menu').setAttribute('aria-label',open?'Close navigation':'Open navigation')};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
function route(){closeMenu();const hash=location.hash||'#home';const isBook=hash.split('?')[0]==='#book';document.body.classList.toggle('booking-active',isBook);if(isBook){quickPicksObserver?.disconnect();page='book';AppointmentBuilder.open(new URLSearchParams(hash.split('?')[1]||'').get('service'));window.scrollTo({top:0,behavior:'instant'});document.title='Build your appointment — Trial Salon Demo'}else{AppointmentBuilder.cleanup();if(page!=='home'){page='home';home()}document.title='TRIAL — Your look. Your energy.';requestAnimationFrame(()=>document.getElementById(hash.slice(1))?.scrollIntoView({behavior:motion()}))}$$('nav a').forEach(a=>{if(a.hash===hash)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
$('#footer').innerHTML=`<a class="logo" href="#home">TRIAL<span>SALON DEMO <i>✳</i></span></a><p>YOUR LOOK. YOUR ENERGY.</p><div><a href="#services">Services</a><a href="#book">Book a look</a><a href="#contact">Contact</a></div><small>© ${new Date().getFullYear()} ${SALON.name} · Fictional business · Concept 02</small><small>STANDARD WEBSITE DEMO · UGX 350,000</small>`;window.addEventListener('hashchange',route);window.addEventListener('scroll',()=>{$('header').classList.toggle('scrolled',scrollY>20)},{passive:true});window.addEventListener('resize',updateGallery);route();
