const SALON={
 name:'Trial Salon Demo',location:'Kololo, Kampala, Uganda',address:'An imagined neighbourhood salon in Kololo, Kampala.',hours:'Monday–Saturday · 9am–7pm',sunday:'Sunday · 10am–4pm',
 contact:{phone:null,email:null,map:'https://www.google.com/maps/search/?api=1&query=Kololo%2C%20Kampala%2C%20Uganda',whatsappShare:'https://wa.me/?text='},
 images:{hero:'assets/images/finished-hairstyle-compressed.jpg',interior:'assets/images/salon-interior-compressed.jpg',styling:'assets/images/women-hair-styling-compressed.jpg',braiding:'assets/images/braiding-service-compressed.jpg',barber:'assets/images/barber-service-compressed.jpg',treatment:'assets/images/hair-treatment-compressed.jpg',nails:'assets/images/manicure-services-compressed.jpg',haircut:'assets/images/finished-mens-haircut-compressed.jpg',atmosphere:'assets/images/salon-atmosphere-compressed.jpg',details:'assets/images/salon-details-compressed.jpg'},
 categories:[
 {id:'hair',name:'Hair',image:'styling',intro:'Fresh hair. Main-character energy.',description:'A fresh shape, a smooth blowout or your big-event look. Let’s find your finish.',services:[{id:'blowout',name:'Signature wash & blowout',price:45000,duration:'60 min',description:'Cleansing wash, nourishing condition and a polished finish.'},{id:'cut',name:'Cut & finish',price:60000,duration:'75 min',description:'Personal consultation, precision shape and styling.'},{id:'occasion',name:'Occasion styling',price:90000,duration:'90 min',description:'An updo or sculpted waves for your big plans.'}]},
 {id:'braids',name:'Braids',image:'braiding',intro:'Big braid energy.',description:'Protective styles with personality. Neat sections, thoughtful technique, your kind of look.',services:[{id:'cornrows',name:'Classic cornrows',price:50000,duration:'90 min',description:'Clean, carefully sectioned cornrows on natural hair.'},{id:'knotless',name:'Knotless braids',price:150000,duration:'4–6 hours',description:'Medium, shoulder-length braids. Extensions priced separately.'},{id:'twists',name:'Two-strand twists',price:80000,duration:'2 hours',description:'Soft, defined twists for natural hair.'}]},
 {id:'barber',name:'Barber',image:'barber',intro:'Stay sharp. Feel fresh.',description:'Precision cuts and clean finishes. Your usual, or something completely new.',services:[{id:'mens-cut',name:'Signature haircut',price:30000,duration:'45 min',description:'Consultation, tailored cut and styling.'},{id:'beard',name:'Beard shape & finish',price:20000,duration:'30 min',description:'Precise shaping and a conditioning finish.'},{id:'cut-beard',name:'Cut & beard ritual',price:45000,duration:'60 min',description:'Signature cut with a complete beard tidy.'}]},
 {id:'treatments',name:'Treatments',image:'treatment',intro:'Hit refresh. From the roots.',description:'Bring your hair back to its happy place with focused scalp and conditioning care.',services:[{id:'deep-condition',name:'Deep conditioning ritual',price:50000,duration:'60 min',description:'Moisture-rich conditioning with gentle steam.'},{id:'scalp',name:'Scalp care & massage',price:40000,duration:'45 min',description:'A cleansing scalp ritual and relaxing massage.'}]},
 {id:'nails',name:'Nails',image:'nails',intro:'Small details. Big mood.',description:'Clean shapes, fresh colour and finishes worth showing off.',services:[{id:'manicure',name:'Classic manicure',price:30000,duration:'45 min',description:'Shaping, cuticle care and regular polish.'},{id:'gel',name:'Gel manicure',price:50000,duration:'60 min',description:'A full manicure with a lasting gel finish.'},{id:'pedicure',name:'Signature pedicure',price:45000,duration:'60 min',description:'A soothing soak, foot care and polish.'}]},
 {id:'beauty',name:'Beauty',image:'details',intro:'Ready for your close-up.',description:'Soft definition or a little extra. Beauty that matches your energy.',services:[{id:'brows',name:'Brow shaping',price:15000,duration:'20 min',description:'Careful shaping to complement your natural features.'},{id:'makeup',name:'Soft-glam makeup',price:100000,duration:'75 min',description:'Fresh, softly defined makeup for your next occasion.'}]}
 ],
 gallery:[{image:'hero',title:'Curls with confidence',category:'Hair'},{image:'haircut',title:'Fresh-cut energy',category:'Barber'},{image:'braiding',title:'Braids that do the talking',category:'Braids'},{image:'nails',title:'A little colour. A lot of mood.',category:'Nails'},{image:'atmosphere',title:'Behind the good vibes',category:'Our space'},{image:'treatment',title:'Your reset moment',category:'Treatments'}],
 testimonials:[{quote:'They took the time to understand what I wanted. I left feeling like myself, just a little more confident.',name:'Nadia K.',service:'Cut & finish'},{quote:'A beautiful space, a warm welcome, and braids that felt as good as they looked.',name:'Patricia A.',service:'Knotless braids'},{quote:'The little details make the difference. This is exactly how a moment of self-care should feel.',name:'Daniel M.',service:'Cut & beard ritual'}]
};
const money=n=>'UGX '+n.toLocaleString('en-UG');
const findService=id=>SALON.categories.flatMap(c=>c.services.map(s=>({...s,categoryId:c.id,category:c.name}))).find(s=>s.id===id);
