const {test}=require('node:test'),assert=require('node:assert/strict'),B=require('./booking-core.js');
const now=new Date('2026-09-05T05:00:00Z');
const draft={serviceId:'blowout',stylistId:'amara',date:'2026-09-07',time:'09:00',name:'Demo Guest',phone:'+256700000000',email:'',notes:''};
test('Kampala date respects UTC+3 at midnight',()=>assert.equal(B.today(new Date('2026-09-05T22:00:00Z')),'2026-09-06'));
test('professionals are restricted by service specialty',()=>{assert.deepEqual(B.professionals('gel').map(p=>p.id),['aisha']);assert.equal(B.professionals('gel','amara').length,0)});
test('off days and invalid date ranges have no slots',()=>{assert.equal(B.slots({...draft,date:'2026-09-06'},[],now).length,0);assert.equal(B.slots({...draft,date:'2026-09-04'},[],now).length,0);assert.equal(B.slots({...draft,date:'2026-12-01'},[],now).length,0)});
test('long services finish within opening hours',()=>{const slots=B.slots({serviceId:'knotless',stylistId:'nakato',date:'2026-09-06'},[],now);assert.equal(slots.length,1);assert.equal(slots[0].time,'10:00');assert.equal(slots[0].end,'16:00')});
test('past times on today are excluded',()=>assert.ok(B.slots({...draft,date:'2026-09-05'},[],new Date('2026-09-05T10:10:00Z')).every(s=>s.time>'13:10')));
test('clashes are excluded; cancellation releases the slot',()=>{const r=B.create(draft,[],now);assert.equal(B.slots(draft,[r],now).some(s=>s.time==='09:00'),false);assert.equal(B.slots(draft,[{...r,status:'cancelled'}],now).some(s=>s.time==='09:00'),true);assert.throws(()=>B.create(draft,[r],now),/no longer available/)});
test('rescheduling excludes own record and keeps its reference',()=>{const r=B.create(draft,[],now);const changed=B.create({...draft,time:'10:00'},[r],now,r);assert.equal(changed.id,r.id);assert.equal(changed.reference,r.reference);assert.equal(changed.time,'10:00')});
test('any-professional option assigns a qualified professional',()=>{const r=B.create({...draft,stylistId:'any'},[],now);assert.equal(r.professional.id,'amara');assert.equal(B.validRecord(r),true)});
test('calendar times are UTC and explicitly labeled as a demo',()=>{const r=B.create(draft,[],now),ics=B.calendar(r);assert.match(ics,/DTSTART:20260907T060000Z/);assert.match(ics,/SUMMARY:DEMO/);assert.match(ics,/STATUS:TENTATIVE/)});
test('repository persists structured data and reports storage errors honestly',()=>{let value=null;const repo=B.repository({getItem:()=>value,setItem:(_,v)=>{value=v}});const r=B.create(draft,[],now);assert.equal(repo.save([r]).persisted,true);assert.equal(repo.load()[0].reference,r.reference);const broken=B.repository({getItem(){throw Error()},setItem(){throw Error()}});assert.equal(broken.save([r]).persisted,false);assert.equal(broken.load().length,1);assert.match(broken.warning,/storage/i)});

test("changing category before Back clears stale service and schedule",()=>{const fs=require("node:fs"),vm=require("node:vm"),source=fs.readFileSync(require.resolve("./app.js"),"utf8");const capture=source.slice(source.indexOf("function capture()"),source.indexOf("function advance("));const context={draft:{category:"hair",serviceId:"blowout",stylistId:"amara",date:"2026-09-07",time:"09:00"},entryProfessional:null,B,$:()=>({}),FormData:class{has(k){return k==="category"}get(){return "nails"}}};vm.runInNewContext(capture+";capture()",context);assert.equal(context.draft.serviceId,"");assert.equal(context.draft.stylistId,"any");assert.equal(context.draft.date,"");assert.equal(context.draft.time,"")});
