const DATA={
 salon:{name:'Trial Salon Demo',location:'Kololo, Kampala',address:'An imagined beauty space in Kololo, Kampala, Uganda.',timezone:'Africa/Kampala',hours:'Monday–Saturday, 9am–7pm',sunday:'Sunday, 10am–4pm',phone:null,email:null,map:'https://www.google.com/maps/search/?api=1&query=Kololo%2C%20Kampala%2C%20Uganda',whatsapp:'https://wa.me/?text='},
 images:{interior:'assets/images/salon-interior-compressed.jpg',styling:'assets/images/women-hair-styling-compressed.jpg',braids:'assets/images/braiding-service-compressed.jpg',barber:'assets/images/barber-service-compressed.jpg',treatment:'assets/images/hair-treatment-compressed.jpg',nails:'assets/images/manicure-services-compressed.jpg',result:'assets/images/finished-hairstyle-compressed.jpg',cut:'assets/images/finished-mens-haircut-compressed.jpg',atmosphere:'assets/images/salon-atmosphere-compressed.jpg',details:'assets/images/salon-details-compressed.jpg'},
 categories:[{id:'hair',name:'Hair styling',image:'styling',intro:'Your hair, beautifully understood.'},{id:'braids',name:'Braiding',image:'braids',intro:'Protective styles. Personal expression.'},{id:'barber',name:'Barbering',image:'barber',intro:'A considered cut. A confident finish.'},{id:'treatments',name:'Hair treatments',image:'treatment',intro:'Care that starts at the roots.'},{id:'nails',name:'Nails',image:'nails',intro:'A little attention to the details.'},{id:'beauty',name:'Beauty',image:'details',intro:'The finishing touches, made personal.'}],
 services:[
 {id:'blowout',category:'hair',name:'Signature wash & blowout',price:45000,minutes:60,duration:'60 min',description:'A cleansing wash, nourishing condition and a polished finish.'},
 {id:'cut',category:'hair',name:'Cut & finish',price:60000,minutes:75,duration:'75 min',description:'A personal consultation, precision shape and finished style.'},
 {id:'occasion',category:'hair',name:'Occasion styling',price:90000,minutes:90,duration:'90 min',description:'An elegant updo or sculpted waves for your special plans.'},
 {id:'cornrows',category:'braids',name:'Classic cornrows',price:50000,minutes:90,duration:'90 min',description:'Clean, carefully sectioned cornrows. Natural hair styles.'},
 {id:'knotless',category:'braids',name:'Knotless braids',price:150000,minutes:360,duration:'4–6 hours',description:'Medium, shoulder-length braids. Extensions priced separately. The demo reserves 6 hours.'},
 {id:'twists',category:'braids',name:'Two-strand twists',price:80000,minutes:120,duration:'2 hours',description:'Soft, defined twists for natural hair.'},
 {id:'mens-cut',category:'barber',name:'Signature haircut',price:30000,minutes:45,duration:'45 min',description:'Consultation, tailored cut and styling.'},
 {id:'beard',category:'barber',name:'Beard shape & finish',price:20000,minutes:30,duration:'30 min',description:'Precise shaping and a conditioning finish.'},
 {id:'cut-beard',category:'barber',name:'Cut & beard ritual',price:45000,minutes:60,duration:'60 min',description:'Our signature cut with a complete beard tidy.'},
 {id:'deep-condition',category:'treatments',name:'Deep conditioning ritual',price:50000,minutes:60,duration:'60 min',description:'A moisture-rich treatment with gentle steam.'},
 {id:'scalp',category:'treatments',name:'Scalp care & massage',price:40000,minutes:45,duration:'45 min',description:'A cleansing scalp ritual and relaxing massage.'},
 {id:'manicure',category:'nails',name:'Classic manicure',price:30000,minutes:45,duration:'45 min',description:'Nail shaping, cuticle care and regular polish.'},
 {id:'gel',category:'nails',name:'Gel manicure',price:50000,minutes:60,duration:'60 min',description:'A full manicure with a lasting gel finish.'},
 {id:'pedicure',category:'nails',name:'Signature pedicure',price:45000,minutes:60,duration:'60 min',description:'A soothing soak, foot care and polish.'},
 {id:'brows',category:'beauty',name:'Brow shaping',price:15000,minutes:20,duration:'20 min',description:'Careful shaping to complement your natural features.'},
 {id:'makeup',category:'beauty',name:'Soft-glam makeup',price:100000,minutes:75,duration:'75 min',description:'Fresh, softly defined makeup for your next occasion.'}],
 stylists:[{"id": "amara", "name": "Amara", "role": "Senior Hairstylist", "categories": ["hair", "treatments"], "specialties": ["Natural Hair", "Hair Styling", "Hair Treatments"], "bio": "Thoughtful styling and nourishing treatments, with time to understand your hair and the finish you have in mind.", "portrait": "assets/images/senior-hairstylst.jpg", "days": [1, 2, 3, 4, 5, 6]}, {"id": "nakato", "name": "Nakato", "role": "Braiding Specialist", "categories": ["braids"], "specialties": ["Braids", "Twists", "Protective Styles"], "bio": "Carefully sectioned braids and twists, with a consultation on your preferred length, finish and everyday care.", "portrait": "assets/images/braiding-specialist.jpg", "days": [0, 2, 3, 4, 5, 6]}, {"id": "daniel", "name": "Daniel", "role": "Barber & Grooming Specialist", "categories": ["barber"], "specialties": ["Haircuts", "Fades", "Beard Grooming"], "bio": "Considered cuts, clean fades and beard shaping, tailored to your style and grooming routine.", "portrait": "assets/images/barber-specialist.jpg", "days": [0, 1, 2, 4, 5, 6]}, {"id": "aisha", "name": "Aisha", "role": "Nail & Beauty Specialist", "categories": ["nails", "beauty"], "specialties": ["Manicure", "Pedicure", "Nail Care", "Beauty Services"], "bio": "Attentive nail care and soft beauty finishes, from your regular manicure to a little preparation for an occasion.", "portrait": "assets/images/beauty-specialist.jpg", "days": [0, 1, 2, 3, 5, 6]}],
 gallery:[{image:'atmosphere',title:'Space to settle in',label:'THE ATMOSPHERE'},{image:'result',title:'Softness, beautifully finished',label:'HAIR & FINISH'},{image:'cut',title:'A fresh point of view',label:'THE BARBER EDIT'},{image:'braids',title:'Every detail, considered',label:'BRAIDING'},{image:'nails',title:'Small moments of colour',label:'NAILS'},{image:'details',title:'The things that make a difference',label:'THE DETAILS'}],
 testimonials:[{name:'Nadia K.',service:'Cut & finish',quote:'They took the time to understand what I wanted. I left feeling like myself, just a little more confident.'},{name:'Patricia A.',service:'Knotless braids',quote:'A beautiful space, a warm welcome, and braids that felt as good as they looked.'},{name:'Daniel M.',service:'Cut & beard ritual',quote:'The little details make the difference. This is exactly how a moment of self-care should feel.'}],
 booking:{schemaVersion:1,storageKey:'trial-salon-option3-appointments-v1',horizonDays:60,interval:30,steps:['Category','Service','Professional','Date','Time','Details','Notes','Review'],statuses:['demo-scheduled','cancelled']}
};
if(typeof module!=='undefined')module.exports=DATA;
